insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1, 'Aliquam erat volutpat. In congue.', 2, 1);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 2, 2);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 2, 3);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5, 4);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (5, 'Aenean sit amet justo. Morbi ut odio.', 1, 5);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (6, 'Donec ut dolor.', 3, 6);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (7, 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 4, 7);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (8, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 5, 8);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (9, 'Mauris ullamcorper purus sit amet nulla.', 1, 9);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (10, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3, 10);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (11, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 4, 11);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (12, 'Duis bibendum.', 3, 12);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (13, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 3, 13);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (14, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 2, 14);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (15, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 1, 15);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (16, 'Morbi ut odio.', 3, 16);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (17, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 5, 17);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (18, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 2, 18);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (19, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 0, 19);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (20, 'Vivamus in felis eu sapien cursus vestibulum.', 5, 20);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (21, 'Duis mattis egestas metus. Aenean fermentum.', 5, 21);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (22, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 0, 22);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (23, 'Suspendisse potenti.', 5, 23);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (24, 'Etiam vel augue.', 4, 24);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (25, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, 25);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (26, 'Curabitur in libero ut massa volutpat convallis.', 4, 26);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (27, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 3, 27);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (28, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 4, 28);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (29, 'Nunc purus. Phasellus in felis.', 4, 29);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (30, 'Pellentesque ultrices mattis odio.', 5, 30);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (31, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 5, 31);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (32, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 4, 32);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (33, 'Duis mattis egestas metus. Aenean fermentum.', 3, 33);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (34, 'Praesent blandit.', 5, 34);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (35, 'Pellentesque ultrices mattis odio.', 0, 35);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (36, 'Phasellus sit amet erat.', 2, 36);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (37, 'Maecenas tincidunt lacus at velit.', 0, 37);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (38, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2, 38);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (39, 'Maecenas rhoncus aliquam lacus.', 0, 39);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (40, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 3, 40);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (41, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 5, 41);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (42, 'Duis at velit eu est congue elementum.', 5, 42);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (43, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 0, 43);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (44, 'Ut tellus.', 1, 44);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (45, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, 45);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (46, 'Aenean sit amet justo.', 4, 46);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (47, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 47);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (48, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 2, 48);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (49, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 1, 49);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (50, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 0, 50);
