insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (72, 'Nader, Jacobi and Purdy', 'Maecenas pulvinar lobortis est.', 2297);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (60, 'Kiehn-Deckow', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 8000);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (86, 'Heller, Miller and Durgan', 'Nulla ac enim.', 6820);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (77, 'Bergnaum-Zemlak', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. ', 9729);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (69, 'Schimmel, Walsh and Boehm', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 2337);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (57, 'Koepp, Balistreri and Padberg', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 6981);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (65, 'Glover Group', 'Nunc purus.', 9874);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (95, 'Krajcik LLC', 'Integer a nibh. In quis justo.', 2138);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (83, 'Mertz, Feeney and Lowe', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 599);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (102, 'Hand, Glover and Roberts', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 6641);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (133, 'Ledner and Sons', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 9719);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (99, 'Labadie-Rau', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 1602);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (93, 'Koepp-Littel', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5167);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (125, 'Pagac, Fritsch and Swift', 'Morbi quis tortor id nulla ultrices aliquet.', 4847);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (100, 'Senger-Ankunding', 'Morbi a ipsum. Integer a nibh.', 6550);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (97, 'Turcotte-Reinger', 'Aenean auctor gravida sem.', 5201);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (82, 'Ruecker, Denesik and Heidenreich', 'Morbi ut odio.', 5735);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (89, 'Johnston-Schimmel', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 1255);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (92, 'Raynor, Stracke and Gleason', 'Nunc rhoncus dui vel sem. Sed sagittis.', 2507);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (76, 'Nitzsche LLC', 'Integer a nibh.', 3768);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (79, 'Mohr, Morissette and McCullough', 'Integer ac neque. Duis bibendum.', 2899);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (107, 'Bailey Inc', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 5281);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (109, 'Walker Inc', 'In hac habitasse platea dictumst.', 2213);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (126, 'Gerlach-Luettgen', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 4023);
insert into empresa (cliente_id, nombre, descripcion, num_empleados) values (129, 'Bosco-Franecki', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 4351);
