insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (51, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 2, 51);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (52, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 5, 52);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (53, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, 53);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (54, 'Donec semper sapien a libero. Nam dui.', 5, 54);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (55, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, 55);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (56, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 5, 56);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (57, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 2, 57);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (58, 'Suspendisse ornare consequat lectus.', 3, 58);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (59, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 59);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (60, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 4, 60);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (61, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 1, 61);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (62, 'Curabitur in libero ut massa volutpat convallis.', 2, 62);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (63, 'Nulla tellus. In sagittis dui vel nisl.', 3, 63);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (64, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 4, 64);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (65, 'Quisque porta volutpat erat.', 1, 65);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (66, 'Suspendisse accumsan tortor quis turpis.', 3, 66);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (67, 'Phasellus sit amet erat. Nulla tempus.', 3, 67);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (68, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 0, 68);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (69, 'Integer a nibh.', 4, 79);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (70, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3, 70);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (71, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 1, 71);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (72, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 1, 72);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (73, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 5, 73);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (74, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2, 74);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (75, 'Maecenas tincidunt lacus at velit.', 1, 75);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (76, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2, 76);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (77, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 5, 77);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (78, 'Donec semper sapien a libero. Nam dui.', 5, 78);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (79, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1, 79);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (80, 'Sed ante.', 4, 80);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (81, 'Nulla ac enim.', 3, 81);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (82, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 3, 82);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (83, 'Nulla ut erat id mauris vulputate elementum.', 5, 83);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (84, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 2, 84);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (85, 'In congue. Etiam justo.', 1, 85);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (86, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3, 86);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (87, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3, 87);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (88, 'Integer ac neque. Duis bibendum.', 1, 88);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (89, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5, 89);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (90, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 2, 90);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (91, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 2, 91);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (92, 'Pellentesque at nulla. Suspendisse potenti.', 3, 92);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (93, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 4, 93);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (94, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 5, 94);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (95, 'Phasellus in felis.', 0, 95);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (96, 'Aliquam non mauris.', 1, 96);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (97, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 3, 97);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (98, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, ', 3, 98);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (99, 'Nullam varius.', 5, 99);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (100, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 4, 100);