insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (51, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 2, 51);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (151, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 5, 151);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (251, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, 251);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (351, 'Donec semper sapien a libero. Nam dui.', 5, 351);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (451, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, 451);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (551, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 5, 551);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (651, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 2, 651);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (751, 'Suspendisse ornare consequat lectus.', 3, 751);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (851, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 851);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (951, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 4, 951);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1051, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 1, 1051);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1151, 'Curabitur in libero ut massa volutpat convallis.', 2, 1151);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1251, 'Nulla tellus. In sagittis dui vel nisl.', 3, 1251);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1351, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 4, 1351);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1451, 'Quisque porta volutpat erat.', 1, 1451);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1551, 'Suspendisse accumsan tortor quis turpis.', 3, 1551);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1651, 'Phasellus sit amet erat. Nulla tempus.', 3, 1651);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1751, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 0, 1751);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1851, 'Integer a nibh.', 4, 1851);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (1951, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3, 1951);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2051, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 4, 2051);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2151, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 1, 2151);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2251, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 1, 2251);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2351, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 5, 2351);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2451, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2, 2451);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2551, 'Maecenas tincidunt lacus at velit.', 1, 2551);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2651, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2, 2651);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2751, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 5, 2751);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2851, 'Donec semper sapien a libero. Nam dui.', 5, 2851);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (2951, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1, 2951);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3051, 'Sed ante.', 4, 3051);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3151, 'Nulla ac enim.', 3, 3151);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3251, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 3, 3251);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3351, 'Nulla ut erat id mauris vulputate elementum.', 5, 3351);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3451, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 2, 3451);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3551, 'In congue. Etiam justo.', 1, 3551);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3651, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3, 3651);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3751, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3, 3751);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3851, 'Integer ac neque. Duis bibendum.', 1, 3851);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (3951, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5, 3951);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4051, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 2, 4051);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4151, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 2, 4151);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4251, 'Pellentesque at nulla. Suspendisse potenti.', 3, 4251);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4351, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 4, 4351);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4451, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 5, 4451);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4551, 'Phasellus in felis.', 0, 4551);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4651, 'Aliquam non mauris.', 1, 4651);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4751, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 3, 4751);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4851, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 3, 4851);
insert into califica_servicio (califica_servicio_id, comentario, estrellas, servicio_id) values (4951, 'Nullam varius.', 5, 4951);
